[versions]
agp = "8.5.2"
kotlin = "2.0.21"
coreKtx = "1.13.1"
gamesActivity = "3.0.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
games-activity = { group = "androidx.games", name = "games-activity", version.ref = "gamesActivity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
